### ISSUE TITLE
doesn't work on mac

### ISSUE THREAD

**Issue by eduard-k** [pjeby/obsidian-symlinks#1] opened 2021-02-15 11:43 UTC
Obsidian does not see symlink with or without plugin.
After enabling the setting "Detect all file extensions", the symlink is visible and opens in Finder.

macOS 11.2.1
Obsidian 0.10.13

**Comment by pjeby** [comment] 2021-02-15 18:17
It looks like Obsidian 0.11.1 will be eliminating the need for this plugin, which is good because I don't really have any way to investigate the issue.  I think the Obsidian devs do, so hopefully it will at least have basic functionality at that point.  ;-)  No guarantees, though, since I believe they're using the same general approach I used in this plugin, so you'll have to work with them if it still doesn't work.  (That being said, the details of their implementation are actually going to be quite different, since I'm patching around their code and they're changing it directly.)  In any case, whatever the problem is, they hopefully can discover and/or fix it on their actual Mac.  ;-)

**Comment by pjeby** [comment] 2021-02-15 18:19
Oh, and all that being said...  you may want to check the permissions of the symlink and whatever directory it's pointing to, as I gather Macs are rather particular about keeping apps from reading other apps' data, and so your symlink target might have more restrictive permissions than the symlink itself.

**Comment by pjeby** [comment] 2021-02-15 18:20
Another way to check: if you rename the symlink (outside Obsidian, with Obsidian open and "detect all file extensions" turned off) does Obsidian suddenly notice it under the new name?

**Comment by pjeby** [comment] 2021-03-06 15:46
Closing this, since Obsidian now has native symlink support.

**Closed as completed by pjeby** 2021-03-06 15:46 UTC
